import { NextRequest, NextResponse } from "next/server"
import { prisma } from "@/lib/db"
import { hash } from "bcryptjs"
import { auth } from "@/lib/auth"
import { applyRateLimit } from "@/lib/rate-limit"
import { randomBytes } from "node:crypto"

const DEMO_EMAIL = "morgan@blackstonepartners.demo"

/** Populate the pitch account with a connected, believable operating history. */
async function seedDemoAccount(user: { id: string; organizationId: string }) {
  const { organizationId, id: userId } = user
  const existing = await prisma.entity.count({ where: { organizationId } })
  if (existing > 0) return

  const now = new Date()
  const days = (offset: number) => new Date(now.getTime() + offset * 86400000)
  const entitySpecs = [
    { name: "Blackstone Properties", type: "COMMERCIAL_PROPERTY", meta: { portfolio: "8 properties across New York, New Jersey, and Connecticut", focus: "Real estate" }, projects: ["Riverfront Plaza lease renewal", "Northeast portfolio capital plan", "2026 property tax cycle", "Hudson Industrial repositioning", "Tenant retention program"], docs: ["Riverfront Plaza — Lease Register", "2025 Property Tax Returns", "Northeast Portfolio Insurance Binder", "Hudson Industrial — Phase I ESA", "Blackstone Properties Board Deck", "Q1 2026 Rent Roll", "Riverfront Plaza — Tenant Improvement Budget", "Hudson Industrial — Environmental Closeout"], contacts: [["Elena Marquez", "Marquez Property Management", "Property Manager"], ["Daniel Cho", "Cho & Patel LLP", "Real Estate Counsel"], ["Priya Nair", "CBRE", "Leasing Advisor"], ["Marcus Bell", "Bell Facilities Group", "Facilities Vendor"], ["Rachel Stein", "Stein Appraisal", "Appraiser"], ["Thomas Reed", "Reed Construction", "General Contractor"]] },
    { name: "BS Ventures", type: "BUSINESS", meta: { industry: "Logistics and supply chain", footprint: "Northeast regional carrier" }, projects: ["Fleet electrification pilot", "Warehouse management rollout", "FY26 operating plan", "Carrier insurance renewal", "Northeast route optimization"], docs: ["BS Ventures — FY26 Operating Plan", "Fleet Lease Schedule", "Warehouse 3PL Agreement", "2025 Audited Financial Statements", "Carrier Insurance Certificate", "Board Meeting — March 2026", "EV Charging Vendor Proposal", "Route Profitability Analysis"], contacts: [["Avery Thompson", "BS Ventures", "President"], ["Jamal Brooks", "Deloitte", "Operations Consultant"], ["Sofia Alvarez", "FleetWorks", "Fleet Account Executive"], ["Nina Kapoor", "Morrison Foerster", "Corporate Counsel"], ["Liam O'Connor", "Eastline Logistics", "Strategic Partner"], ["Marcus Bell", "Bell Facilities Group", "Facilities Vendor"]] },
    { name: "Blackstone Investments", type: "INVESTMENT", meta: { strategy: "Public equities, private equity, and venture positions", aum: "$184M" }, projects: ["Q2 allocation review", "Mosaic Fund IV diligence", "Liquidity and tax planning", "Annual investor reporting", "Private markets pipeline"], docs: ["Investment Policy Statement — 2026", "Mosaic Fund IV — Subscription Agreement", "Q1 Performance Attribution", "Private Holdings Cap Table", "K-1 Collection Tracker", "Investment Committee Deck", "Mosaic Fund IV — Diligence Notes", "Liquidity Forecast — 2026"], contacts: [["Victor Lang", "Lang Capital Advisors", "Portfolio Manager"], ["Rebecca Wu", "Harris Williams", "Investment Banker"], ["Daniel Cho", "Cho & Patel LLP", "Tax Counsel"], ["Maya Shah", "Mosaic Capital", "Partner"], ["Gregory Foster", "Northern Trust", "Relationship Manager"], ["Olivia Park", "Crestview Accounting", "Controller"]] },
    { name: "BS Foundation", type: "OTHER", meta: { mission: "Family foundation supporting education and local resilience", status: "Private foundation" }, projects: ["2026 grantmaking cycle", "Community resilience grants", "Annual 990-PF filing", "Scholarship partner review", "Board succession planning"], docs: ["2026 Grantmaking Guidelines", "2025 Form 990-PF Filing", "Community Resilience Grant Docket", "Foundation Investment Policy", "Board Minutes — February 2026", "Scholarship Partner MOU", "Grant Compliance Checklist", "2026 Scholarship Applications"], contacts: [["Caroline Webb", "BS Foundation", "Executive Director"], ["Janet Ellis", "Ellis & Hart CPAs", "Foundation Accountant"], ["Maya Shah", "Mosaic Capital", "Board Member"], ["Andre Williams", "Harbor Youth Network", "Grantee Partner"], ["Grace Kim", "Education Forward", "Program Director"], ["Daniel Cho", "Cho & Patel LLP", "Legal Counsel"]] },
    { name: "BS Hospitality", type: "BUSINESS", meta: { industry: "Hotels and restaurants", footprint: "Boutique hotels and destination dining" }, projects: ["Harbor House renovation", "2026 hospitality operating plan", "Restaurant concept launch", "Guest experience modernization", "Seasonal staffing plan"], docs: ["Harbor House — Management Agreement", "2026 Hospitality Operating Plan", "Restaurant Vendor Master List", "Hotel Property Insurance Binder", "Guest Experience Standards", "Hospitality Board Review — Q1 2026", "Harbor House — Renovation Drawings", "Food Safety Inspection Log"], contacts: [["Isabella Rossi", "BS Hospitality", "Managing Director"], ["Marcus Bell", "Bell Facilities Group", "Facilities Vendor"], ["Tara Nguyen", "Marriott Advisory Services", "Hospitality Consultant"], ["Daniel Cho", "Cho & Patel LLP", "Real Estate Counsel"], ["Luis Mendoza", "Culinary Concepts Group", "Restaurant Operator"], ["Hannah Price", "Lockton", "Insurance Broker"]] },
    { name: "Blackstone Development", type: "COMMERCIAL_PROPERTY", meta: { portfolio: "Commercial development pipeline across the Northeast", focus: "Real estate development" }, projects: ["Broadway mixed-use entitlement", "Newark logistics campus", "2026 development pipeline", "Construction financing program", "Transit district feasibility"], docs: ["Broadway District — Entitlement Plan", "Newark Campus — Site Assessment", "Development Pipeline — 2026", "Construction Loan Term Sheet", "Environmental Review Register", "General Contractor Prequalification", "Broadway Traffic Study", "Newark Campus — Concept Plans"], contacts: [["Noah Bennett", "Blackstone Development", "Development Director"], ["Rachel Stein", "Stein Appraisal", "Appraiser"], ["Daniel Cho", "Cho & Patel LLP", "Development Counsel"], ["Marcus Bell", "Bell Facilities Group", "Facilities Vendor"], ["Priya Nair", "CBRE", "Leasing Advisor"], ["Owen Gallagher", "Turner Construction", "Project Executive"]] },
    { name: "BS Technology", type: "BUSINESS", meta: { industry: "SaaS and workflow automation", footprint: "Enterprise software subsidiary" }, projects: ["Operion platform release", "Enterprise security program", "Customer success expansion", "FY26 product roadmap", "Data warehouse migration"], docs: ["Operion Product Roadmap — 2026", "SOC 2 Readiness Assessment", "Enterprise Master Services Agreement", "FY26 Technology Budget", "Information Security Policy", "Customer Success Playbook", "Incident Response Runbook", "Q2 Product Analytics"], contacts: [["Ethan Cole", "BS Technology", "Chief Executive Officer"], ["Sofia Alvarez", "FleetWorks", "Strategic Customer"], ["Nina Kapoor", "Morrison Foerster", "Technology Counsel"], ["Jamal Brooks", "Deloitte", "Operations Consultant"], ["Leah Morgan", "CloudScale", "Infrastructure Partner"], ["Victor Lang", "Lang Capital Advisors", "Board Advisor"]] },
    { name: "Blackstone Family Office", type: "OTHER", meta: { mission: "Integrated wealth management and family services", status: "Private family office" }, projects: ["2026 family wealth plan", "Next-generation governance", "Household operations modernization", "Family travel and philanthropy calendar", "Estate planning refresh"], docs: ["Family Investment Policy — 2026", "Estate Planning Coordination Memo", "Household Staffing Handbook", "Private Aviation Insurance Schedule", "Family Governance Charter", "Annual Wealth Review — 2025", "Family Travel Calendar", "Trust Administration Checklist"], contacts: [["Morgan Webb", "Blackstone Partners LLC", "Principal"], ["Olivia Park", "Crestview Accounting", "Controller"], ["Daniel Cho", "Cho & Patel LLP", "Tax Counsel"], ["Grace Kim", "Education Forward", "Philanthropy Advisor"], ["Gregory Foster", "Northern Trust", "Relationship Manager"], ["Isabella Rossi", "BS Hospitality", "Family Services Partner"]] },
  ]

  const createdEntities: { id: string; name: string }[] = []
  const createdProjects: { id: string; entityId: string }[] = []
  const createdTasks: { id: string; entityId: string; title: string }[] = []
  const statusCycle: string[] = ["DONE", "DONE", "DONE", "IN_PROGRESS", "IN_PROGRESS", "IN_PROGRESS", "IN_PROGRESS", "IN_PROGRESS", "TODO", "TODO", "TODO", "TODO", "BLOCKED", "BLOCKED", "WAITING_ON", "WAITING_ON", "READY_FOR_REVIEW", "TODO", "IN_PROGRESS", "DONE"]
  const taskNames = ["Review monthly operating report", "Approve vendor invoices", "Prepare leadership update", "Confirm insurance renewals", "Collect outstanding documents from counsel", "Reconcile cash activity", "Schedule stakeholder follow-up", "Update risk register", "Review budget variance", "Share action items", "Validate compliance calendar", "Request revised forecast", "Archive executed agreements", "Prepare next board packet", "Confirm decision owners", "Review open questions with advisor", "Finalize weekly status notes", "Check project dependencies", "Refresh KPI dashboard", "Send approval package", "Coordinate site walk", "Compare vendor bids", "Document decision log", "Escalate blocked item", "Review draft for Morgan", "Confirm filing receipt", "Prepare next meeting agenda", "Close completed workstream"]
  const commentText = ["Morgan, I reviewed this — can you confirm the numbers on page 3?", "Confirmed, sent to Daniel for legal review.", "I will reconcile the remaining variance before Thursday's leadership review.", "Thanks — I added the supporting schedule and moved this to ready for review."]

  for (const [entityIndex, spec] of entitySpecs.entries()) {
    const entity = await prisma.entity.create({ data: { organizationId, name: spec.name, type: spec.type, metadata: JSON.stringify(spec.meta), isSample: true, createdAt: days(-42 + entityIndex) } })
    createdEntities.push(entity)
    const projects = await Promise.all(spec.projects.map((name, i) => prisma.project.create({ data: { organizationId, entityId: entity.id, name, description: `Morgan-led workstream for ${spec.name}: ${name}.`, status: i === 3 ? "ON_HOLD" : i === 4 ? "COMPLETED" : "ACTIVE", phase: ["OPERATIONS", "DUE_DILIGENCE", "CLOSEOUT", "ACQUISITION", "CONSTRUCTION"][i], progress: i === 4 ? 100 : 18 + ((i * 17 + entityIndex * 9) % 68), budget: 25000 + i * 17500 + entityIndex * 4200, startDate: days(-55 + i * 9), targetDate: days(i === 4 ? -8 : 10 + i * 13), isSample: true } })))
    createdProjects.push(...projects.map((project) => ({ id: project.id, entityId: entity.id })))
    const tasks = await Promise.all(taskNames.map((base, i) => { const due = i % 9 === 0 ? days(-(i % 6 + 2)) : i % 7 === 0 ? days(-4) : days(2 + ((i * 5 + entityIndex) % 35)); const status = statusCycle[i % statusCycle.length]; return prisma.task.create({ data: { organizationId, entityId: entity.id, projectId: projects[i % projects.length].id, title: `${base} — ${spec.name}`, description: `Coordinate and close this item across the ${spec.name} operating file.`, status, priority: i % 20 === 0 ? "CRITICAL" : i % 5 < 2 ? "HIGH" : i % 5 < 4 ? "MEDIUM" : "LOW", dueDate: due, assigneeId: userId, createdById: userId, category: spec.type, aiSuggestion: i === 0 ? `Bring this to Morgan's next review: deadline is ${due.toLocaleDateString("en-US", { month: "short", day: "numeric" })}.` : undefined, notes: status === "BLOCKED" ? "Waiting on external counsel or vendor confirmation." : status === "DONE" ? "Completed and filed for the operating record." : undefined, createdAt: days(-28 + (i % 14)), isSample: true } }) }))
    createdTasks.push(...tasks.map(t => ({ id: t.id, entityId: entity.id, title: t.title })))
    await prisma.document.createMany({ data: spec.docs.map((name, i) => ({ organizationId, entityId: entity.id, projectId: projects[i % projects.length].id, name, type: name.includes("Lease") || name.includes("Agreement") || name.includes("MOU") || name.includes("Term Sheet") ? "CONTRACT" : name.includes("Tax") || name.includes("990") || name.includes("K-1") ? "TAX" : name.includes("Board") || name.includes("Committee") || name.includes("Minutes") || name.includes("Deck") ? "PDF" : "FINANCIAL_STATEMENT", notes: JSON.stringify({ summary: `Operating record for ${spec.name}.`, fileSize: `${(0.4 + ((i + entityIndex) % 8) * 0.73).toFixed(1)} MB`, needsReview: i % 4 === 1 }), uploadedById: userId, createdAt: days(-35 + i * 3), updatedAt: days(-5 + (i % 5)), isSample: true })) })
    await prisma.contact.createMany({ data: spec.contacts.map(([name, company, position], i) => ({ organizationId, entityId: entity.id, name, company, position, email: `${name.toLowerCase().replace(/[^a-z]+/g, ".")}@${company.toLowerCase().replace(/[^a-z]+/g, "")}.com`, phone: `212-555-${String(1400 + entityIndex * 100 + i).slice(-4)}`, notes: `Primary ${position.toLowerCase()} for ${spec.name}; cross-referenced in the operating directory.`, isSample: true })) })
  }

  for (const task of createdTasks.filter((_, i) => i % 7 < 4)) await prisma.comment.createMany({ data: commentText.slice(0, 2 + (task.id.charCodeAt(0) % 3)).map((content, i) => ({ content, taskId: task.id, authorId: userId, organizationId, createdAt: days(-(5 - i)) })) })
  const meetingTemplates: readonly [string, number][] = [["Operating review", -14], ["Risk and deadline triage", -4], ["Stakeholder decision meeting", 6], ["Monthly planning session", 17], ["Executive follow-up", 29]]
  for (const [entityIndex, entity] of createdEntities.entries()) for (const [i, [label, offset]] of meetingTemplates.entries()) await prisma.meeting.create({ data: { organizationId, projectId: createdProjects[entityIndex * 5 + (i % 5)].id, title: `${label} — ${entity.name}`, date: days(offset + entityIndex), location: i % 2 ? "Video conference" : `${entity.name} office`, notes: offset < 0 ? `Decisions captured: reviewed open risks, assigned owners, and confirmed next steps for ${entity.name}. Follow-up due next operating review.` : `Agenda: priorities, risks, approvals, and next actions for ${entity.name}.`, isSample: true, createdAt: days(offset < 0 ? offset - 3 : -3) } })
  await prisma.notification.createMany({ data: [["DEADLINE", "Lease renewal needs attention", "Riverfront Plaza lease renewal is due in 12 days.", false], ["OVERDUE", "4 tasks are past due", "Review overdue workstream items before tomorrow's briefing.", false], ["MENTION", "Daniel Cho mentioned you", "Daniel asked for the signed Newark financing schedule.", false], ["COMMENT", "New comment on your task", "Elena replied to the Riverfront Plaza action item.", true], ["REMINDER", "Investment committee tomorrow", "Q2 allocation review starts at 10:00 AM.", true], ["STALLED", "Fleet pilot is blocked", "FleetWorks has not confirmed the charging installation date.", false], ["COMPLETED", "Security review completed", "SOC 2 readiness assessment was marked complete.", true], ["WAITING", "Approval needed", "The hospitality vendor bid is waiting on your decision.", false], ["RENEWAL", "Insurance binder expires soon", "Review the property insurance renewal packet.", true], ["ASSIGNED", "New task assigned", "Review the family office estate planning memo.", false]].map(([type, title, message, read], i) => ({ organizationId, userId, type, title, message, link: type === "COMMENT" ? "/tasks" : "/home", read, readAt: read ? days(-i - 1) : undefined, createdAt: days(-i * 2) })) })
  await prisma.auditLog.createMany({ data: [...createdEntities.map((e, i) => ({ organizationId, userId, action: "CREATE", entity: "Entity", entityId: e.id, details: JSON.stringify({ name: e.name }), createdAt: days(-14 + i) })), ...createdProjects.slice(0, 24).map((p, i) => ({ organizationId, userId, action: i % 4 === 0 ? "UPDATE" : "CREATE", entity: "Project", entityId: p.id, details: JSON.stringify({ source: "demo operating history" }), createdAt: days(-12 + (i % 12)) })), ...createdTasks.slice(0, 48).map((t, i) => ({ organizationId, userId, action: i % 5 === 0 ? "UPDATE" : "CREATE", entity: "Task", entityId: t.id, details: JSON.stringify({ title: t.title }), createdAt: days(-10 + (i % 10)) }))] })
}

export async function POST(_req: NextRequest) {
  const limit = await applyRateLimit(_req, { maxRequests: 3, windowMs: 5 * 60 * 1000 })
  if (limit) return limit

  const session = await auth()
  if (!session?.user || !(session.user as { isSuperAdmin?: boolean }).isSuperAdmin) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
  }

  try {
    const adminEmail = "Hello@operion.online"
    let adminUser = await prisma.user.findUnique({ where: { email: adminEmail } })
    if (!adminUser) {
      const adminOrg = await prisma.organization.create({ data: { name: "Operion", slug: "operion" } })
      adminUser = await prisma.user.create({ data: { email: adminEmail, name: "Admin", passwordHash: await hash(process.env.SUPER_ADMIN_INITIAL_PASSWORD || randomBytes(32).toString("base64url"), 10), role: "OWNER", organizationId: adminOrg.id, isSuperAdmin: true } })
    }
    let demoUser = await prisma.user.findUnique({ where: { email: DEMO_EMAIL } })
    if (!demoUser) {
      const demoOrg = await prisma.organization.create({ data: { name: "Blackstone Partners LLC", slug: "blackstone-partners-" + Date.now(), subscriptionTier: "SOLO", subscriptionStatus: "ACTIVE" } })
      demoUser = await prisma.user.create({ data: { email: DEMO_EMAIL, name: "Morgan Webb", passwordHash: await hash("demo123!", 10), role: "OWNER", organizationId: demoOrg.id } })
    }
    await seedDemoAccount(demoUser)
    return NextResponse.json({ status: "ok", admin: adminUser.email, demo: demoUser.email })
  } catch (error) { return NextResponse.json({ error: String(error) }, { status: 500 }) }
}
